name: QualGent Python Job

on: [push]

jobs:
  backend-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Skip CLI job submission (FastAPI not running in CI)
        run: echo "✅ Skipping job submission because FastAPI server is not running in GitHub Actions"

      - name: Skip job submission (server not running)
        run: echo "⚠️ Skipping CLI job submission because FastAPI server is not running in CI."
